apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment
  template:
    metadata:
      labels:
        app: deployment
    spec:
      containers:
        - name: fiap-tech-challenge
          image: 'ufoindustry/tech-challenge-produto:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: "1m"
          env:
            - name: SPRING_DATASOURCE_URL
              value: mongodb://mongodb:27017/produtos
            - name: SPRING_DATA_MONGODB_USERNAME
              value: myuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: secret
            - name: SPRING_DATA_MONGODB_PASSWORD
              value: create